name: Run mkdocs
on:
  push:
    branches:
      - main

permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pgnquant for optimize plugin
        run: sudo apt-get install pngquant
    
      - name: Set up Python runtime
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install Python dependencies
        run: pip install mkdocs-monorepo-plugin mkdocs-redirects mkdocs-git-authors-plugin mkdocs-git-revision-date-localized-plugin mkdocs-git-committers-plugin-2 Pillow 'mkdocs-material[imaging]' mike

      - name: Set up build cache
        uses: actions/cache@v4
        with:
          key: ${{ github.ref }}
          path: .cache

      - name: Install Insiders build
        env:
          MKDOCS_TOKEN: ${{ secrets.MKDOCS_SECRET }}
        run: pip install git+https://${MKDOCS_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git

      - name: Install Insiders build
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }} 
        run: pip install git+https://${GH_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git
#      - run: mkdocs gh-deploy --force
#      - run: mike deploy --push --update-aliases 0.1 latest
      - name: Setup Docs Deploy
        run: git config --global user.name "Docs Deploy"
      - name: Setup Docs Email
        run: git config --global user.email "lori.crotser@sparkfun.com"
      - name: Build Docs Website
        run: mike deploy --push develop